name: Free Windows RDP 6H
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup RDP
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString "Password123!" -AsPlainText -Force)
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Write-Output "✅ RDP Aktif. IP: $(hostname -I)"
